### PR TITLE
Correct handling of event-level serverHost attribute

### PR DESCRIPTION
**Pull request by Kami**
This pull request adds new ``dont_use_session_level_serverhost_attribute`` config option which can be used in combination with custom logstash filter which sets special ``__origServerHost`` attribute.

For example:

```
...
filter {
  mutate {
    add_field => { "__origServerHost" => "%{[host][name]}" }
  }
}
...
```

When this config option is set, we won't send ``serverHost`` as part of session level attributes and event level ``__origServerHost`` attribute will be used (if set) to correctly set ``serverHost`` session level attribute for each of the events.

This means "Sources" will be correctly populated with those serverHost values.

## Background, Context

Current version of the plugin has multiple issues as far as handling ``serverHost`` goes. 

I assume that's because of the incorrect understanding of how special ``serverHost`` attribute works and as such, incorrect implementation.

Currently, the plugin will set ``serverHost`` attribute on the event level (aka it will be event level attribute).

The problem with that is that since it's an event level attribute, it will be treated exactly the same as any other "regular" event level attribute (aka it won't be used for Sources functionality).

Server host is only handled correctly (as designed) for Source functionality either if it's set as part of session level attributes (which means all the events as part of the same addEvents request need to contain same serverHost value) or if it's set on the event level using special ``__origServerHost`` attribute.

## TODO / Open Questions

- [ ] Audit whole ``serverHost`` functionality and fix + simplify it
- [ ] One option would be to expose ``serverHost`` to the end users (e.g. as a field name), but internally we could rename it to the ``__origServerHost``
- [ ] Should rename existing ``serverHost`` even level field we set internally to ``__origServerHost``? I would almost argue for yes, downside is that the change is backward incompatible, but plugin is still in beta.

### CODE REVIEW

**Comment by Kami** [comment]
OK, so I had another look at the plugin and here are the changes we could do.

First to document the facts / existing behavior.

``serverHost`` attribute will only be used correctly and as expected (aka will be used for "Sources" functionality) in one of the following scenarios:

1. ``serverHost`` attribute is specified as part of a top-level session attribute
2.  ``serverHost`` is specified as part of a special ``__origServerHost`` event level attribute (to make this a bit less confusing, we can consider ``__origServerHost`` as implementation detail and expose ``serverHost`` to the end users)
3. Top session level ``serverHost`` has the highest priority. This means if session level ``serverHost`` is specified, ``__origServerHost`` event-level attribute value will be ignored and session level value will be used.
4. If ``serverHost`` is specified as part of session and event level attribute, ``serverHost`` value will only be populated on the event level, but as a regular event attribute (which means that basically session level ``serverHost`` value will be ignored - that's important because that happens today where code basically always adds static "Logstash" ``serverHost`` attribute to each event / record).

In other scenarios (``serverHost`` specified as event level attribute either directly or via refenced log file and specified on the top level ``logs`` attribute), it will be treated as any other regular event attribute.

Now to the proposed behavior / changes.

1. I propose to keep end user-visible event level attribute called ``serverHost``, but to ensure it works correctly (and the way it was probably assumed it works by the original author plugin), rename it internally to ``__origServerHost`` (if ``serverHost`` is present on the record).

2. I propose to default the top level session ``serverHost`` attribute value to node hostname and not setting event level ``serverHost`` attribute to ``Logstash`` (if custom serverHost attribute is not set on the record / event) since that value is confusing and doesn't work as most people would expect.

3. If ``serverHost`` record attribute is set, we should not send session level ``serverHost`` attribute (per the facts section above, session level one has precedence). This applies to scenarios where user manually sets this attribute as part of a logstash filter or similar.

Technically this change is not really backward incompatible because if user previously did ``serverHost = "foo"`` query, this will continue to work as it did in the past (but instead of that attribute being regular event level attribute, it will be session level attribute which will also populate "Sources" correctly).

Because of that, I'm not sure if it's strictly necessary to make those changes opt-in and put them behind a feature flag. 

But in any case, we should first release beta version, test it ourselves (share it with some users) and once confirmed it's working as expected, bump major version and remove beta identified from the plugin version.

Oh and technically ``__origServerHost`` will result in session splitting on the server side for different serverHost values, but by default, each /addEvents request will still only have this set to a single value (node hostname) so the default behavior shouldn't change and it shouldn't put any additional load on the server side.

---


Since it seems like a lot of code was copied over from fluentd plugin, it would also be good to verify fluentd plugin behavior and check if any changes are needed or desired there as well.

/cc @yanscalyr

**Comment by Kami** [comment]
I pushed commit which implements changes per my comment above - 4c49e28baf6524b490023ac56a62648454d1f5c1.

The behavior can perhaps be best understood by looking at the unit tests at https://github.com/scalyr/logstash-output-scalyr/blob/9070cdda9140017a119a49dddafbd788f8bfb89e/spec/logstash/outputs/scalyr_spec.rb#L562.

While working on it, I noticed common "serverHost" attribute "folding" into "logs" attribute was also broken (aka we didn't correctly reference common attribute in the logs entry for all the batch events, but duplicated it on the event level).

**Review by yanscalyr — APPROVED** [review]
LGTM

**Comment by Kami** [comment]
@yanscalyr Per discussion on slack, I pushed a change for that additional edge case - d40ccb0

Since behavior without this change will likely work for a big chunk of users, this change is opt-in since it likely adds non trivial amount of overhead (I didn't add a microbenchark for it at this point since it's not on by default, but I can add it in the future, if needed).

**Comment by yanscalyr** [comment]
@Kami That change changes the events after our size checks which means in theory we could outgrow our configured limit if I'm not mistaken. Is there any reason we couldn't do this before the size check? The method would need to work off of a single event rather than a collection of them is the only difference I can see.

**Comment by Kami** [comment]
@yanscalyr Good catch.

We can't really easily do it before we have processed all the events, because we only want to set that attributes on the events without it, in case any other event defines custom serverHost (in case it doesn't, we don't need this logic and we can just use session value). And we don't really know which event / if any will define that (it could be last event in the batch).

Having said that, I think it's unlikely to hit the limit since we have limit set in the plugin to 5.5 MB and the actual limit on the server side is 6 MB so there is some leeway. If the issue does arise in the future, I'll redo the logic then.

**Comment by Kami** [comment]
I'm a bit OCD so I decided to add micro benchmark regardless - 3f2c6e72ea52bd33fdc9806a5b715bfaaef4279c (https://app.circleci.com/pipelines/github/scalyr/logstash-output-scalyr/491/workflows/ee7c99dd-6044-46c8-97ce-5fa7a7f2afd5/jobs/1714/parallel-runs/0/steps/0-103).

While working on this change, I also noticed some of the benchmarks don't correctly use different dataset for each benchmark run iteration (this can affect results since JIT may optimize more if the same data is used and may result in non representative and underestimated results / timings).

I fixed it in 8e99f8ba615264a97f0258871b40c25002da6f48.

/cc @yanscalyr

**Pull request merged**
