### PR TITLE
Additional micro benchmarks, add sampling for per-event metrics, fix flatten event values metric handling, add new event attributes count metric

### PR DESCRIPTION
**Pull request by Kami**
This pull request updates existing flattening micro benchmarks to cover some more scenarios and also benchmarks JSON dumps to see if that is faster than flattening the dict recursively.

In addition to that, it adds support for sampling for per-event level metrics (right now that's serialization time and I will also add another metric for number of attributes in an event).

It's a good idea to do sampling on event level metrics since there could be many of those coming in per second (and now we use Quantile implementation which is a bit more expensive than a simple counter based metric).

### CODE REVIEW

**Review by yanscalyr — APPROVED** [review]
I don't see any issues except that we sample 5% of events by default and not 0.5% as the comment states.
Besides that LGTM

**Comment by Kami** [comment]
I also added a new (nightly) Circle CI job which runs smoketests against latest stable version from ruby gems.

**Comment by yanscalyr** [comment]
I see our circle config refers to a `yarnsh/agent-testing:latest` docker hub image, which is something I used for testing a year ago supposedly. I also assume its related to the Agent and not logstash by the name but I can't be sure, any idea what that's doing?

**Comment by Kami** [comment]
@yanscalyr Yeah, we use image from your Docker hub account for some of the test containers so ideally we would move this to Scalyr account in the near future.

"Luckily" that's just for the verifier container where I used the same "workaround" as we use in scalyr-agent-2 repo. For the actual container which runs logstash + plugin (the one I modified in this PR), we build it on Circle CI so I didn't need to use more workarounds.

**Comment by Kami** [comment]
Fixed the ``0.5%`` typo, thanks.

**Pull request merged**
